//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace LAP.Resources {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Shapes {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Shapes() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("LAP.Resources.Shapes", typeof(Shapes).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   厳密に型指定されたこのリソース クラスを使用して、すべての検索リソースに対し、
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot;?&gt;
        ///&lt;!--This file is NOT compatible with Silverlight--&gt;
        ///&lt;Viewbox xmlns=&quot;http://schemas.microsoft.com/winfx/2006/xaml/presentation&quot; Stretch=&quot;Uniform&quot;&gt;
        ///  &lt;Canvas Name=&quot;svg2&quot; Width=&quot;65&quot; Height=&quot;65&quot;&gt;
        ///    &lt;Canvas.RenderTransform&gt;
        ///      &lt;TranslateTransform X=&quot;0&quot; Y=&quot;0&quot;/&gt;
        ///    &lt;/Canvas.RenderTransform&gt;
        ///    &lt;Canvas.Resources/&gt;
        ///    &lt;!--Unknown tag: metadata--&gt;
        ///    &lt;!--Unknown tag: sodipodi:namedview--&gt;
        ///    &lt;Canvas Name=&quot;g10&quot;&gt;
        ///      &lt;Canvas.RenderTransform&gt;
        ///        &lt;MatrixTransform Ma [残りの文字列は切り詰められました]&quot;; に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Disc {
            get {
                return ResourceManager.GetString("Disc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot;?&gt;
        ///&lt;!--This file is NOT compatible with Silverlight--&gt;
        ///&lt;Viewbox xmlns=&quot;http://schemas.microsoft.com/winfx/2006/xaml/presentation&quot; Stretch=&quot;Uniform&quot;&gt;
        ///  &lt;Canvas Name=&quot;svg3336&quot; Width=&quot;65&quot; Height=&quot;33.75&quot;&gt;
        ///    &lt;Canvas.RenderTransform&gt;
        ///      &lt;TranslateTransform X=&quot;0&quot; Y=&quot;0&quot;/&gt;
        ///    &lt;/Canvas.RenderTransform&gt;
        ///    &lt;Canvas.Resources/&gt;
        ///    &lt;!--Unknown tag: metadata--&gt;
        ///    &lt;!--Unknown tag: sodipodi:namedview--&gt;
        ///    &lt;Canvas Name=&quot;g3344&quot;&gt;
        ///      &lt;Canvas.RenderTransform&gt;
        ///        &lt;MatrixTran [残りの文字列は切り詰められました]&quot;; に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Eye {
            get {
                return ResourceManager.GetString("Eye", resourceCulture);
            }
        }
        
        /// <summary>
        ///   &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot;?&gt;
        ///&lt;!--This file is NOT compatible with Silverlight--&gt;
        ///&lt;Viewbox xmlns=&quot;http://schemas.microsoft.com/winfx/2006/xaml/presentation&quot; Stretch=&quot;Uniform&quot;&gt;
        ///  &lt;Canvas Name=&quot;svg2&quot; Width=&quot;60&quot; Height=&quot;66.25&quot;&gt;
        ///    &lt;Canvas.RenderTransform&gt;
        ///      &lt;TranslateTransform X=&quot;0&quot; Y=&quot;0&quot;/&gt;
        ///    &lt;/Canvas.RenderTransform&gt;
        ///    &lt;Canvas.Resources/&gt;
        ///    &lt;!--Unknown tag: metadata--&gt;
        ///    &lt;!--Unknown tag: sodipodi:namedview--&gt;
        ///    &lt;Canvas Name=&quot;g10&quot;&gt;
        ///      &lt;Canvas.RenderTransform&gt;
        ///        &lt;MatrixTransform [残りの文字列は切り詰められました]&quot;; に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Playlist {
            get {
                return ResourceManager.GetString("Playlist", resourceCulture);
            }
        }
    }
}
